"""empty message

Revision ID: 197df27c2ae7
Revises: 385f3e7faa18
Create Date: 2022-08-07 13:52:35.127325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '197df27c2ae7'
down_revision = '385f3e7faa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoplefavourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'people_id')
    )
    op.drop_table('people_favourites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_favourites',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='people_favourites_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='people_favourites_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'people_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('peoplefavourites')
    # ### end Alembic commands ###
